name: Deploy the docs site
on:
  - push
  - workflow_dispatch
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt-get install python3-pip python3-setuptools python3-wheel --assume-yes --install-recommends
            sudo pip3 install -r requirements.txt .

      - name: Build the docs site
        run: |
          mkdocs build

      - name: Upload docs site artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Setup GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v2

      - name: Deploy docs site to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v1
